language: php

php:
  - "5.4"
  - "5.5"
  - "5.6"
  - "7.0"
  - "7.4"
  - "8.0"
  - "8.1"
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - composer update
  - composer install

script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/coveralls -v
